TodoApp/Todo/urls.py
from django.urls import path
from . views import (TodoListView, TodoUpdateView, TodoDeleteView)

app_name = 'todo_app'

urlpatterns = [
    path('', TodoListView.as_view(), name='todo-list'),
    path('update/<pk>/', TodoUpdateView.as_view(), name='update'),
    path('delete/<pk>/', TodoDeleteView.as_view(), name='delete'),
]

TodoApp/TodoApp/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Todo.urls')),
    path('', include('accounts.urls')),
]

TodoApp/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts_app'

urlpatterns = [
    path('sign-up/', views.SignUpFormView.as_view(), name='sign-up'),
    path('login/', views.LoginFormView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

TodoApp/Todo/models.py
from django.db import models
from django.contrib.auth.models import User

from . managers import TodoManager

class Todo(models.Model):
    name = models.CharField("Nombre" ,max_length=20)
    description = models.CharField("Descripcion", max_length=100)
    user = models.ForeignKey(User, verbose_name="Usuario", on_delete=models.CASCADE)
    create_at = models.DateTimeField("Creado el", auto_now_add=True)
    update_at = models.DateTimeField("Actualizado el", auto_now=True)

    objects = TodoManager()

    class Meta:
        ordering = ['create_at']

    def __str__(self):
        return self.name

TodoApp/accounts/models.py
from django.db import models

# Create your models here.

TodoApp/Todo/forms.py
from django import  forms

from . models import Todo

class TodoForm(forms.ModelForm):
    """Form definition for Todo."""

    class Meta:
        """Meta definition for Todoform."""

        model = Todo
        fields = ('name', 'description')
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            )
        }

class TodoUpdateForm(forms.ModelForm):
    """Form definition for Todo."""

    class Meta:
        """Meta definition for Todoform."""

        model = Todo
        fields = ('name','description')
        widgets = {
            'name': forms.TextInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            )
        }

TodoApp/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.contrib.auth import authenticate


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(
        label = 'Contraseña',
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Ingrese su contraseña'}),
    )
    password2 = forms.CharField(
        label = 'Contraseña (confirmación)',
        widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Repita su contraseña'}),
    )
    class Meta:
        model = User
        fields = ['username', 'password1', 'password2']

        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'Ingrese su nombre de usuario'
                }
            )
        }

class LoginForm(forms.Form):
    username = forms.CharField(
        label='Nombre de usuario',
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder' : 'Ingrese su nombre de usuario',
                'class': 'form-control'
            }
        )
    )
    password = forms.CharField(
        label='Contrasena',
        required=True,
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Ingrese su contrasena',
                'class': 'form-control'
            }
        )
    )
    def clean(self):
        cleaned_data = super(LoginForm, self).clean()
        username = self.cleaned_data['username']
        password =  self.cleaned_data['password']
        if not authenticate(username=username, password=password):
            raise forms.ValidationError('Los datos del usuario no son correctos')
        return self.cleaned_data

TodoApp/Todo/views.py
from django.views.generic import (
    ListView, FormView, UpdateView,
    DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls.base import reverse_lazy
from django.contrib import messages

from . models import Todo
from . forms import TodoForm, TodoUpdateForm

class CrearTodoFormView(FormView):
    form_class = TodoForm
    success_url = reverse_lazy('todo_app:todo-list')
    def form_valid(self, form):
        user = self.request.user
        Todo.objects.create(
            name = form.cleaned_data['name'],
            description = form.cleaned_data['description'],
            user = user
        )
        return super(CrearTodoFormView, self).form_valid(form)


class TodoListView(CrearTodoFormView ,LoginRequiredMixin ,ListView):
    model = Todo
    template_name = "todo_list.html"
    context_object_name = 'todo'
    login_url = reverse_lazy('accounts_app:sign-up')

    def get_queryset(self):
        user = self.request.user
        return Todo.objects.listarTareasActuales(user)


class TodoUpdateView(UpdateView):
    model = Todo
    template_name = "update_todo.html"
    form_class = TodoUpdateForm
    success_url = reverse_lazy('todo_app:todo-list')

    def form_valid(self, form):
        todo = form.save(commit=False)
        todo.save()
        messages.success(self.request, f'La tarea {todo.name} ah sido actualizada correctamente')
        return super(TodoUpdateView, self).form_valid(form)

class TodoDeleteView(DeleteView):
    model = Todo
    template_name = "delete_todo.html"
    success_url = reverse_lazy('todo_app:todo-list')

TodoApp/accounts/views.py
from django.views.generic import FormView, View
from django.urls.base import reverse_lazy, reverse
from django.http import HttpResponseRedirect
from django.contrib import messages
# login
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.models import User
# 
from . forms import SignUpForm, LoginForm

class SignUpFormView(FormView):
    template_name = 'sign_up.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts_app:login')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password1 = form.cleaned_data['password1']

        user = User.objects.create(
            username = username
        )
        user.set_password(password1)
        user.save()
        messages.success(self.request, f'Se ah creado con exito al usuario {username}')
        return super(SignUpFormView, self).form_valid(form)

class LoginFormView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = reverse_lazy('todo_app:todo-list')

    def form_valid(self, form):
        user = authenticate(
            username = form.cleaned_data['username'],
            password = form.cleaned_data['password']
        )
        login(self.request, user)
        messages.success(self.request, f'Bienvenido {user.username}')
        return super(LoginFormView, self).form_valid(form)

class LogoutView(View):

    def get(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(
            reverse(
                'accounts_app:login'
            )
        )

TodoApp/Todo/templates/base/base.html
<!DOCTYPE html> {% load static %}
<html lang="es">
<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
{% block content %}
        
{% endblock content %}
</body>
</html>

TodoApp/Todo/templates/base/header.html
<nav class="navbar navbar-expand-sm navbar-light ">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="mynavbar">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'todo_app:todo-list' %}">Lista de tareas</a>
          </li>
        </ul>
        
        {% if user.username %}
          <h4>usuario: <strong>{{user.username}}</strong></h4>
          <div style="padding: 5px;"></div>
          <a href="{% url 'accounts_app:logout' %}" class="btn btn-outline-danger">Cerrar sesion</a>
        {% else %}
          <a href="{% url 'accounts_app:sign-up' %}" class="btn btn-outline-primary">Registrarse</a>
          <div style="padding: 5px;"></div>
          <a href="{% url 'accounts_app:login' %}" class="btn btn-outline-primary">Iniciar sesion</a>
        {% endif %}
      </div>
    </div>
  </nav>
  <hr>

TodoApp/Todo/templates/delete_todo.html
{% extends 'base/base.html' %}{% load static %}

{% block title %}
    Lista de tareas - TodoApp
{% endblock title %}

{% block content %}
<div class="container">
{% include 'base/header.html' %}   
<div style="text-align: left; margin: 0 auto; max-width: 50%;">
    <h4>Estas seguro de eliminar la tarea <strong>{{object.name}}</strong></h4>
    <form action="" method="post">
        {% csrf_token %}
        <div style="padding-top: 10px;"></div>
        <button type="submit" class="btn btn-danger">Eliminar tarea</button>
    </form>
</div>    
{% endblock %}

</div>

TodoApp/Todo/templates/todo_list.html
{% extends 'base/base.html' %}{% load static %}

{% block title %}
    Lista de tareas - TodoApp
{% endblock title %}

{% block content %}
<div class="container">
{% include 'base/header.html' %}   
{% if messages %}
    <div class="alert alert-success" style="text-align: center;">
        {% for m in messages %}
            {{m}}
        {% endfor %}
    </div>
{% endif %}
<div style="padding: 5px;"></div>
<table class="table table-borderless">
    <thead>
      <tr>
        <th>Nombre de la tarea</th>
        <th>Descripcion</th>
        <th>Fecha de creacion</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    {% for t in todo %}
      <tr>
        <td>{{t.name}}</td>
        <td>{{t.description}}</td>
        <td>{{t.create_at}}</td>
        <td>
            <a href="{% url 'todo_app:update' t.id %}" class="btn btn-warning">Actualizar</a>
            <a href="{% url 'todo_app:delete' t.id %}" class="btn btn-danger">Eliminar</a>
        </td>
      </tr>
    {% empty %}
    <div class="alert alert-danger" style="text-align: center;">
        <strong>No se han creado tareas</strong> 
      </div>
    {% endfor %}
    </tbody>
  </table>
  <hr>
  <div style="padding: 5px;"></div>
    <div style="text-align: left; margin: 0 auto; max-width: 50%;">
        <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3 mt-3">
                <label class="form-label" >{{field.label}}</label>
                {{field}}
            </div>
            {% endfor %}
            <div style="padding-top: 10px;"></div>
            <button type="submit" class="btn btn-outline-primary">Crear tarea</button>
        </form>
    </div>    
        
</div>
        
{% endblock content %}

TodoApp/Todo/templates/update_todo.html
{% extends 'base/base.html' %}{% load static %}

{% block title %}
    Lista de tareas - TodoApp
{% endblock title %}

{% block content %}
<div class="container">
{% include 'base/header.html' %}   
<div style="text-align: left; margin: 0 auto; max-width: 50%;">
    <form action="" method="post">
        {% csrf_token %}
        {% for field in form %}
        <div class="mb-3 mt-3">
            <label class="form-label" >{{field.label}}</label>
            {{field}}
        </div>
        {% endfor %}
        <div style="padding-top: 10px;"></div>
        <button type="submit" class="btn btn-warning">Actualizar tarea</button>
    </form>
</div>    
{% endblock %}

</div>

TodoApp/accounts/templates/login.html
{% extends 'base/base.html' %}{% load static %}

{% block title %}
    Login - TodoApp
{% endblock title %}

{% block content %}
<div class="container">
{% include 'base/header.html' %}

{% if messages %}
    <div class="alert alert-success" style="text-align: center;">
        {% for m in messages %}
            {{m}}
        {% endfor %}
    </div>
{% endif %}
    
{% if form.errors %}
<div class="alert alert-danger">
    <strong>{{form.errors}}</strong> 
</div>
{% endif %}
<div style="text-align: left; margin: 0 auto; max-width: 50%;">
    <form action="" method="post">
        {% csrf_token %}
            {% for field in form %}
            <div class="mb-3 mt-3">
                <label class="form-label" >{{field.label}}</label>
                {{field}}
            </div>
        {% endfor %}
        <div style="padding-top: 10px;"></div>
        <button type="submit" class="btn btn-outline-primary">Iniciar sesion</button>
    </form>
{% endblock content %}
</div>

TodoApp/accounts/templates/sign_up.html
{% extends 'base/base.html' %}{% load static %}

{% block title %}
    Registro - TodoApp
{% endblock title %}

{% block content %}
<div class="container">
{% include 'base/header.html' %}
{% if form.errors %}
    <div class="alert alert-danger">
        <strong>{{form.errors}}</strong> 
    </div>
{% endif %}
    <div style="text-align: left; margin: 0 auto; max-width: 50%;">
        <form action="" method="post">
            {% csrf_token %}
                {% for field in form %}
                <div class="mb-3 mt-3">
                    <label class="form-label" >{{field.label}}</label>
                    {{field}}
                </div>
            {% endfor %}
            <div style="padding-top: 10px;"></div>
            <button type="submit" class="btn btn-outline-primary">Registrarse</button>
        </form>
    </div>
    <div style="padding-top: 10px;"></div>
    <div class="alert alert-primary" style="text-align: center;">
        <strong>IMPORTANTE!</strong> debe estar registrado para ver y crear sus tareas
    </div>
</div>
{% endblock content %}
    
    